### PR TITLE
Yusuf zuri

### PR DESCRIPTION
**Pull request by yousouph246**
added addchild.html to the pages folder
added addchild.css to the css folder
and updated the images in the folder above

### CODE REVIEW

**Comment by yousouph246** [comment]
done

**Comment by Felistus** [comment]
@yousouph246 Good work so far. You are doing great.
Please kindly resolve the conflicts in this Pull Request.
Please pull from the upstream dev branch and then include your changes and push again. follow the workflow properly so you can avoid future conflicts.
Good work once again.

**Comment by yousouph246** [comment]
done some adjustments

**Comment by yousouph246** [comment]
Added the book appointment button to the landing page by adjusting the index css and html

**Pull request closed without merging**
